milvus-io/milvus-storage

- cpp/Makefile
> feat(makefile): add a Makefile in cpp (#12)

- cpp/src/common/fs_util.cpp
- cpp/src/common/fs_util.h
- cpp/src/common/utils.cpp
- cpp/src/common/utils.h
- cpp/src/storage/schema.cpp
- cpp/src/storage/space.cpp
- cpp/src/storage/space.h
- cpp/test/schema_test.cpp
- cpp/test/space_test.cpp
- add unit test for space by cpp.
- add conversion function for uri to path.
- add offset field when building scalar schema.
- change schema test for the new offset column.
> feat(space): refactor and improve Storage Space functionality

- go/common/constant.go
- go/common/log/field.go
- go/common/log/log.go
- go/common/log/log_test.go
- go/common/log/options.go
- go/common/utils/utils.go
- go/go.mod
- go/go.sum
- go/io/fs/local_fs.go
- go/storage/default_space.go
- go/storage/manifest/manifest.go
- go/storage/manifest/manifest_test.go
- go/storage/schema/schema.go
- go/storage/schema/schema_test.go
- go/storage/space_test.go
- fix write bug, mv don't need to delete temp file.
- add some unit tests.
- fix fs open bug, check and auto create dir.
- refactoring space, add mutex.
> feat(log):add zap library and logging capabilities

- cpp/include/milvus-storage/common/arrow_util.h
- cpp/include/milvus-storage/common/status.h
- cpp/include/milvus-storage/format/parquet/file_writer.h
- cpp/include/milvus-storage/format/writer.h
- cpp/include/milvus-storage/writer/column_group.h
- cpp/include/milvus-storage/writer/column_group_writer.h
- cpp/include/milvus-storage/writer/splitter/indices_based_splitter.h
- cpp/include/milvus-storage/writer/splitter/splitter_plugin.h
- cpp/include/milvus-storage/writer/stream_writer.h
- cpp/src/common/arrow_util.cpp
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/writer/column_group.cpp
- cpp/src/writer/column_group_writer.cpp
- cpp/src/writer/splitter/indices_based_splitter.cpp
- cpp/src/writer/splitter/size_based_splitter.cpp
- cpp/src/writer/stream_writer.cpp
- cpp/test/writer/column_group_test.cpp
- cpp/test/writer/splitter/indices_based_splitter_test.cpp
- cpp/test/writer/stream_writer_test.cpp
> feat: add stream writer

- cpp/include/milvus-storage/common/arrow_util.h
- cpp/include/milvus-storage/packed/reader.h
- cpp/src/common/arrow_util.cpp
- cpp/src/packed/reader.cpp
- cpp/test/packed/reader_test.cpp
> feat: adding packed reader

- cpp/include/milvus-storage/packed/reader.h
- cpp/src/packed/reader.cpp
- cpp/test/packed/reader_test.cpp
- cpp/test/writer/splitter/indices_based_splitter_test.cpp
- cpp/test/writer/splitter/size_based_splitter_test.cpp
- cpp/test/writer/splitter/splitter_test_base.h
> clean up reader and writer

- OWNERS
- cpp/conanfile.py
- cpp/include/milvus-storage/format/parquet/file_writer.h
- cpp/include/milvus-storage/packed/column_group.h
- cpp/include/milvus-storage/packed/column_group_writer.h
- cpp/include/milvus-storage/packed/reader.h
- cpp/include/milvus-storage/packed/writer.h
- cpp/src/common/fs_util.cpp
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/packed/column_group.cpp
- cpp/src/packed/column_group_writer.cpp
- cpp/src/packed/reader.cpp
- cpp/src/packed/splitter/size_based_splitter.cpp
- cpp/src/packed/writer.cpp
- cpp/test/packed/column_group_test.cpp
- cpp/test/packed/packed_integration_test.cpp
- cpp/test/packed/reader_test.cpp
issue: #131 
feat:
- Fix packed writer row group size
- Fix packed reader row group memory size by reading from file metadata
- Add logging
> enhance: fix packed reader and writer

- cpp/include/milvus-storage/packed/chunk_manager.h
- cpp/include/milvus-storage/packed/reader.h
- cpp/include/milvus-storage/packed/writer.h
- cpp/src/packed/chunk_manager.cpp
- cpp/src/packed/reader.cpp
- cpp/src/packed/writer.cpp
- cpp/test/packed/chunk_manager_test.cpp
- cpp/test/packed/packed_integration_test.cpp
> enhance: support multiple reading row groups to avoid missing data

- cpp/include/milvus-storage/packed/column_group_writer.h
- cpp/src/packed/column_group_writer.cpp
- cpp/src/packed/reader.cpp
- cpp/test/packed/packed_integration_test.cpp
> enhance: fix ut for large batches

- .github/workflows/cpp-ci.yml
- cpp/CMakeLists.txt
- cpp/conanfile.py
- cpp/include/milvus-storage/common/fs_util.h
- cpp/include/milvus-storage/storage/space.h
- cpp/src/common/fs_util.cpp
- cpp/src/storage/space.cpp
- cpp/test/packed/packed_integration_test.cpp
- cpp/test/packed/reader_test.cpp
> add s3 fs validation

- cpp/include/milvus-storage/common/fs_util.h
- cpp/include/milvus-storage/format/parquet/file_writer.h
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/packed/writer.cpp
- cpp/test/packed/packed_integration_test.cpp
> fix packed writer memory limit

- cpp/include/milvus-storage/common/fs_util.h
- cpp/include/milvus-storage/packed/splitter/size_based_splitter.h
- cpp/include/milvus-storage/packed/writer.h
- cpp/src/common/fs_util.cpp
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/packed/splitter/size_based_splitter.cpp
- cpp/src/packed/writer.cpp
- cpp/test/packed/packed_integration_test.cpp
> enhance: Init buffer for packed writer

- cpp/src/common/fs_util.cpp
- cpp/test/packed/packed_test_base.h
> add random data for ut

- cpp/src/packed/reader.cpp
- cpp/src/packed/writer.cpp
- cpp/test/packed/one_file_test.cpp
> fix packed writer closer

- cpp/include/milvus-storage/filesystem/azure/azure_fs.h
- cpp/include/milvus-storage/filesystem/s3/s3_fs.h
- cpp/include/milvus-storage/filter/filter.h
- cpp/include/milvus-storage/packed/column_group_writer.h
- cpp/include/milvus-storage/packed/reader.h
- cpp/include/milvus-storage/packed/utils/config.h
- cpp/include/milvus-storage/reader/common/delete_reader.h
- cpp/src/filesystem/fs.cpp
- cpp/src/packed/chunk_manager.cpp
- cpp/src/packed/column_group_writer.cpp
- cpp/test/packed/one_file_test.cpp
- cpp/test/packed/packed_integration_test.cpp
- cpp/test/packed/packed_test_base.h
> [fix]: Fix azure connection and clean up test

- cpp/CMakeLists.txt
> fix: Undefined symbol in libmilvus_storage.so

- cpp/CMakeLists.txt
issue: https://github.com/milvus-io/milvus-storage/issues/158
> fix: cmake required protobuf

- cpp/benchmark/benchmark_packed.cpp
- cpp/include/milvus-storage/common/constants.h
- cpp/include/milvus-storage/filesystem/azure/azure_fs.h
- cpp/include/milvus-storage/filesystem/fs.h
- cpp/include/milvus-storage/filesystem/s3/AliyunCredentialsProvider.h
- cpp/include/milvus-storage/filesystem/s3/AliyunSTSClient.h
- cpp/include/milvus-storage/filesystem/s3/TencentCloudCredentialsProvider.h
- cpp/include/milvus-storage/filesystem/s3/TencentCloudSTSClient.h
- cpp/include/milvus-storage/filesystem/s3/s3_fs.h
- cpp/src/filesystem/azure/azure_fs.cpp
- cpp/src/filesystem/fs.cpp
- cpp/src/filesystem/s3/AliyunCredentialsProvider.cpp
- cpp/src/filesystem/s3/AliyunSTSClient.cpp
- cpp/src/filesystem/s3/TencentCloudCredentialsProvider.cpp
- cpp/src/filesystem/s3/TencentCloudSTSClient.cpp
- cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
- cpp/src/filesystem/s3/s3_fs.cpp
- cpp/src/storage/space.cpp
- cpp/test/common/arrow_utils_test.cpp
- cpp/test/filesystem/s3_fs_test.cpp
- cpp/test/multi_files_sequential_reader_test.cpp
- cpp/test/packed/packed_test_base.h
- cpp/test/space_test.cpp
> feat: arrow s3 file system support tls and iam

- cpp/src/filesystem/azure/azure_fs.cpp
- cpp/src/filesystem/s3/s3_fs.cpp
- cpp/src/format/parquet/file_writer.cpp
- cpp/test/filesystem/s3_fs_test.cpp
- cpp/test/format/parquet/file_reader_test.cpp
- cpp/test/packed/packed_integration_test.cpp
- cpp/test/packed/packed_test_base.h
> feat: support azure filesystem with iam

- cpp/CMakeLists.txt
- cpp/conanfile.py
- cpp/include/milvus-storage/filesystem/s3/multi_part_upload_s3_fs.h
- cpp/include/milvus-storage/filesystem/s3/s3_fs.h
- cpp/src/filesystem/azure/azure_fs.cpp
- cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
- cpp/src/filesystem/s3/s3_fs.cpp
> feat: support gcs iam

- .github/workflows/cpp-ci.yml
- cpp/CMakeLists.txt
- cpp/Makefile
- cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/packed/reader.cpp
- cpp/src/storage/space.cpp
- cpp/test/CMakeLists.txt
- cpp/test/filesystem/s3_fs_test.cpp
- cpp/test/manifest_test.cpp
- cpp/test/space_test.cpp
- cpp/test/test_util.cpp
related: https://github.com/milvus-io/milvus-storage/issues/176
> enhance: support asan and fix memory leak

- cpp/include/milvus-storage/common/constants.h
- cpp/include/milvus-storage/common/metadata.h
- cpp/include/milvus-storage/format/parquet/file_reader.h
- cpp/include/milvus-storage/format/parquet/file_writer.h
- cpp/src/common/metadata.cpp
- cpp/src/format/parquet/file_reader.cpp
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/packed/reader.cpp
- cpp/test/format/parquet/file_reader_test.cpp
> feat: row group and storage version metadata

- cpp/include/milvus-storage/common/arrow_util.h
- cpp/include/milvus-storage/format/parquet/file_reader.h
- cpp/src/common/arrow_util.cpp
- cpp/src/format/parquet/file_reader.cpp
- cpp/test/format/parquet/file_reader_test.cpp
> fix: file row group reader api

- cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
> fix: workaround compatibility issue between AWS SDK and MinIO [GH-45304]

- cpp/src/format/parquet/file_reader.cpp
- cpp/src/packed/reader.cpp
- cpp/test/format/parquet/file_reader_test.cpp
> fix: file row group reader reads despite insufficient memory

- cpp/include/milvus-storage/format/parquet/file_writer.h
- cpp/include/milvus-storage/packed/reader.h
- cpp/include/milvus-storage/packed/writer.h
- cpp/src/common/arrow_util.cpp
- cpp/src/format/parquet/file_reader.cpp
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/packed/column_group_writer.cpp
- cpp/src/packed/reader.cpp
- cpp/src/packed/writer.cpp
- cpp/test/format/parquet/file_reader_test.cpp
- cpp/test/format/parquet/file_writer_test.cpp
- cpp/test/packed/packed_integration_test.cpp
* Fix segmentation faults when reading schemas with non-existent columns
* Add robust schema evolution support for missing columns (returns null columns with correct row counts)
* Use proper indexing between file readers and original paths
* Enhanc test coverage for multiple row groups, nullable fields, and complex schema evolution scenarios
> enhance: handle reader and writer corner case

- cpp/include/milvus-storage/packed/reader.h
- cpp/src/packed/chunk_manager.cpp
- cpp/src/packed/reader.cpp
- cpp/test/packed/packed_test_base.h
related: https://github.com/milvus-io/milvus/issues/43310
> fix: packed reader memory limit read

- cpp/include/milvus-storage/packed/column_group.h
- cpp/src/packed/reader.cpp
related: https://github.com/milvus-io/milvus/issues/43310
> fix packed reader missing data

- cpp/src/format/parquet/file_writer.cpp
Related to milvus-io/milvus#43752
> enhance: Use filesystem to create parent dir

- cpp/src/filesystem/s3/s3_fs.cpp
Related to milvus-io/milvus#39173
Missed change for PR #241
> enhance: Set ExtendedS3Option bucket name

- cpp/include/milvus-storage/common/constants.h
- cpp/include/milvus-storage/filesystem/s3/multi_part_upload_s3_fs.h
- cpp/src/format/parquet/file_writer.cpp
- cpp/src/packed/writer.cpp
related: https://github.com/milvus-io/milvus/issues/43869
> fix: azure fs should not part upload

- cpp/include/milvus-storage/filesystem/s3/multi_part_upload_s3_fs.h
- cpp/src/filesystem/s3/multi_part_upload_s3_fs.cpp
- cpp/src/filesystem/s3/s3_fs.cpp
- cpp/test/s3_client_metrics_test.cpp
> enhance: Revert bucket name push down PRs

- cpp/src/filesystem/s3/s3_fs.cpp
related: https://github.com/milvus-io/milvus/issues/44481
> fix: force virtual host for oss and cos
